### ISSUE TITLE
CMV does not suport namespace prefix

### ISSUE THREAD

**Issue by cessda-bitbucket-importer** [cessda/cessda.cmv.core#111]
**Original report on BitBucket by Olof Olsson.**

----------------------------------------

Got contacted by Adrian Dușa regarding validation of DDI 2.5 output from SledgeHammer \([see attached file](https://github.com/cessda/cessda.cmv/files/10425948/14552aea47ba4eeaa6ab7d5325cc8de0.zip)\).

This tool uses namespace prefix for all DDI 2.5 elements witch is fine if you do a xsd validation but in The CMV validator it seems like elements cant be found \(in this example `/codeBook/stdyDscr/citation/titlStmt/titl`\).

I don't know any other tools or organization using namespace prefixes for DDI 2.X but it might be good to cover this use case.

**Comment by matthew-morris-cessda** [comment]
The namespace configuration should be read from the DDI profile document.

**Comment by matthew-morris-cessda** [comment]
Blocked on https://github.com/cessda/cessda.metadata.profiles/issues/177
